In [21]:
from model import Model, train_one_batch
from model import *
from train_utils import Train_on_Batch

In [ ]:
# validate()

In [22]:
from typing import Any
from lightning.pytorch.utilities.types import STEP_OUTPUT
import torch
import torch.nn as nn
from torch.nn import Embedding, Linear, LSTM, Module

from torch import tensor as T

import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import Dataset

import lightning as L
from torch.utils.data import TensorDataset, DataLoader


import matplotlib.pyplot as plt
import seaborn as sns

import typing


import yaml

In [23]:
word_list_train = "data/250k_train.txt"
word_list_val = "data/250k_test.txt"
number_games = 10
model = Model("big_embed")


In [25]:

# training_data_generator = Train_on_Batch(word_list_train, model, 10000)
test_data_generator = Train_on_Batch(word_list_val, model, 500) 
validate_set = test_data_generator.generate_data()

In [28]:
train_for = 5000 #! games
for i in {pbar := tqdm(range(500, train_for+500, 500))}:
    #! generate data for 500 games at a time, train on it and mve ahead.
    t_d_g = Train_on_Batch(word_list_train, model, i)
    training_data = t_d_g.generate_data()
    model.to('cuda')
    training_data = [i.to('cuda') for i in training_data]
    train_one_batch(model, training_data[0], training_data[1], training_data[2], 500, torch.optim.SGD(model.parameters(), lr = 5e-4))
    pbar.set_description("%.3f Val Loss" % )


AttributeError: 'tuple' object has no attribute 'generate_data'

In [13]:
# model = Model("base_config")
model.to('cpu')
DataGen = Train_on_Batch(word_list, model, 1000)
dataset = DataGen.generate_data()
# dataset = (i.to('cuda') for i in dataset)

_________
Now Play
Tries remaining : 6
e
['e']
tensor([27,  5, 27, 27, 27, 27, 27, 27, 27])
_e_______
Tries remaining : 6
e
['e']
tensor([27,  5, 27, 27, 27, 27, 27, 27, 27])
_e_______
Tries remaining : 5
e
['e']
tensor([27,  5, 27, 27, 27, 27, 27, 27, 27])
_e_______
Tries remaining : 4
e
['e']
tensor([27,  5, 27, 27, 27, 27, 27, 27, 27])
_e_______
Tries remaining : 3
e
['e']
tensor([27,  5, 27, 27, 27, 27, 27, 27, 27])
_e_______
Tries remaining : 2
e
['e']
tensor([27,  5, 27, 27, 27, 27, 27, 27, 27])
_e_______
Tries remaining : 1
e
['e']
tensor([27,  5, 27, 27, 27, 27, 27, 27, 27])
_e_______
febrility
_____________
Now Play
Tries remaining : 6
e
['e']
tensor([27,  5, 27, 27, 27, 27, 27, 27, 27, 27, 27,  5, 27])
_e_________e_
Tries remaining : 6
e
['e']
tensor([27,  5, 27, 27, 27, 27, 27, 27, 27, 27, 27,  5, 27])
_e_________e_
Tries remaining : 5
e
['e']
tensor([27,  5, 27, 27, 27, 27, 27, 27, 27, 27, 27,  5, 27])
_e_________e_
Tries remaining : 4
e
['e']
tensor([27,  5, 27, 27, 27, 27

In [14]:
model.to('cuda')
dataset = [i.to('cuda') for i in dataset]

In [15]:
print([dataset[x].size() for x in range(3)])

[torch.Size([7938, 30]), torch.Size([7938, 26]), torch.Size([7938, 26])]


In [16]:

train_one_batch(model, dataset[0], dataset[1], dataset[2], 5000, torch.optim.SGD(model.parameters(),lr=1e-3))

  0%|          | 0/5000 [00:00<?, ?it/s]

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
27

KeyboardInterrupt: 

In [8]:
model.to('cpu')
DataGen.generate_data()

_______
Now Play
Tries remaining : 6
e
['e']
tensor([27, 27, 27,  5, 27, 27, 27])
___e___
Tries remaining : 6
a
['a', 'e']
tensor([27, 27, 27,  5, 27, 27, 27])
___e___
Tries remaining : 5
a
['a', 'e']
tensor([27, 27, 27,  5, 27, 27, 27])
___e___
Tries remaining : 4
a
['a', 'e']
tensor([27, 27, 27,  5, 27, 27, 27])
___e___
Tries remaining : 3
a
['a', 'e']
tensor([27, 27, 27,  5, 27, 27, 27])
___e___
Tries remaining : 2
a
['a', 'e']
tensor([27, 27, 27,  5, 27, 27, 27])
___e___
Tries remaining : 1
a
['a', 'e']
tensor([27, 27, 27,  5, 27, 27, 27])
___e___
toreros
______
Now Play
Tries remaining : 6
e
['e']
tensor([27, 27, 27, 27, 27, 27])
______
Tries remaining : 5
e
['e']
tensor([27, 27, 27, 27, 27, 27])
______
Tries remaining : 4
e
['e']
tensor([27, 27, 27, 27, 27, 27])
______
Tries remaining : 3
e
['e']
tensor([27, 27, 27, 27, 27, 27])
______
Tries remaining : 2
e
['e']
tensor([27, 27, 27, 27, 27, 27])
______
Tries remaining : 1
e
['e']
tensor([27, 27, 27, 27, 27, 27])
______
ryazan
___

(tensor([[ 0,  0,  0,  ..., 27, 27, 27],
         [ 0,  0,  0,  ..., 27, 27, 27],
         [ 0,  0,  0,  ..., 27, 27, 27],
         ...,
         [ 0,  0,  0,  ..., 27,  5, 27],
         [ 0,  0,  0,  ..., 27,  5, 27],
         [ 0,  0,  0,  ..., 27,  5, 27]]),
 tensor([[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 1.],
         [0., 0., 0.,  ..., 0., 0., 1.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]]),
 tensor([[0.0909, 0.0000, 0.0909,  ..., 0.0909, 0.0000, 0.0000],
         [0.0909, 0.0000, 0.0909,  ..., 0.0909, 0.0000, 0.0000],
         [0.0909, 0.0000, 0.0909,  ..., 0.0909, 0.0000, 0.0000],
         ...,
         [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000]]))