In [1]:
from model import Model, train_one_batch
from train_utils import Train_on_Batch

In [2]:
from typing import Any
from lightning.pytorch.utilities.types import STEP_OUTPUT
import torch
import torch.nn as nn
from torch.nn import Embedding, Linear, LSTM, Module

from torch import tensor as T

import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import Dataset

import lightning as L
from torch.utils.data import TensorDataset, DataLoader


import matplotlib.pyplot as plt
import seaborn as sns

import typing


import yaml

In [3]:
word_list = "data/250k.txt"
number_games = 10


In [9]:
# model = Model("base_config")
DataGen = Train_on_Batch(word_list, model, 1000)
dataset = DataGen.generate_data()

____
Now Play
Tries remaining : 6
a
['a']
tensor([ 1, 27, 27, 27])
a___
Tries remaining : 6
a
['a']
tensor([ 1, 27, 27, 27])
a___
Tries remaining : 5
a
['a']
tensor([ 1, 27, 27, 27])
a___
Tries remaining : 4
a
['a']
tensor([ 1, 27, 27, 27])
a___
Tries remaining : 3
a
['a']
tensor([ 1, 27, 27, 27])
a___
Tries remaining : 2
a
['a']
tensor([ 1, 27, 27, 27])
a___
Tries remaining : 1
a
['a']
tensor([ 1, 27, 27, 27])
a___
ause
_______________
Now Play
Tries remaining : 6
a
['a']
tensor([27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27,  1, 27, 27, 27])
___________a___
Tries remaining : 6
o
['a', 'o']
tensor([27, 27, 27, 27, 27, 15, 27, 27, 27, 27, 27,  1, 27, 27, 27])
_____o_____a___
Tries remaining : 6
o
['a', 'o']
tensor([27, 27, 27, 27, 27, 15, 27, 27, 27, 27, 27,  1, 27, 27, 27])
_____o_____a___
Tries remaining : 5
o
['a', 'o']
tensor([27, 27, 27, 27, 27, 15, 27, 27, 27, 27, 27,  1, 27, 27, 27])
_____o_____a___
Tries remaining : 4
o
['a', 'o']
tensor([27, 27, 27, 27, 27, 15, 27, 27, 27, 27, 27

In [10]:
print([dataset[x].size() for x in range(3)])

[torch.Size([8453, 30]), torch.Size([8453, 26]), torch.Size([8453, 26])]


In [15]:

train_one_batch(model.to('cuda'), dataset[0], dataset[1], dataset[2], 10000, torch.optim.Adam(model.parameters(),lr=1e-3))

  0%|          | 0/10000 [00:00<?, ?it/s]

0


RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument index in method wrapper_CUDA__index_select)

In [16]:
DataGen.generate_data()

__________
Now Play
Tries remaining : 6
c
['c']
tensor([27, 27, 27, 27, 27, 27, 27, 27, 27, 27])
__________
Tries remaining : 5
c
['c']
tensor([27, 27, 27, 27, 27, 27, 27, 27, 27, 27])
__________
Tries remaining : 4
c
['c']
tensor([27, 27, 27, 27, 27, 27, 27, 27, 27, 27])
__________
Tries remaining : 3
c
['c']
tensor([27, 27, 27, 27, 27, 27, 27, 27, 27, 27])
__________
Tries remaining : 2
c
['c']
tensor([27, 27, 27, 27, 27, 27, 27, 27, 27, 27])
__________
Tries remaining : 1
c
['c']
tensor([27, 27, 27, 27, 27, 27, 27, 27, 27, 27])
__________
postfixing
_______
Now Play
Tries remaining : 6
c
['c']
tensor([27, 27, 27, 27, 27, 27, 27])
_______
Tries remaining : 5
c
['c']
tensor([27, 27, 27, 27, 27, 27, 27])
_______
Tries remaining : 4
c
['c']
tensor([27, 27, 27, 27, 27, 27, 27])
_______
Tries remaining : 3
c
['c']
tensor([27, 27, 27, 27, 27, 27, 27])
_______
Tries remaining : 2
c
['c']
tensor([27, 27, 27, 27, 27, 27, 27])
_______
Tries remaining : 1
c
['c']
tensor([27, 27, 27, 27, 27, 27,

(tensor([[ 0,  0,  0,  ..., 27, 27, 27],
         [ 0,  0,  0,  ..., 27, 27, 27],
         [ 0,  0,  0,  ..., 27, 27, 27],
         ...,
         [ 0,  0,  0,  ..., 27, 27,  3],
         [ 0,  0,  0,  ..., 27, 27,  3],
         [ 0,  0,  0,  ..., 27, 27,  3]]),
 tensor([[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 1., 0.,  ..., 0., 0., 0.],
         [0., 1., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 1.,  ..., 0., 0., 0.],
         [0., 0., 1.,  ..., 0., 0., 0.],
         [0., 0., 1.,  ..., 0., 0., 0.]]),
 tensor([[0.1000, 0.0000, 0.1000,  ..., 0.0000, 0.1000, 0.0000],
         [0.1000, 0.0000, 0.1000,  ..., 0.0000, 0.1000, 0.0000],
         [0.1000, 0.0000, 0.1000,  ..., 0.0000, 0.1000, 0.0000],
         ...,
         [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000]]))