### You know the drill.

In [1]:
!git clone https://github.com/juggernautjha/rnn_testing.git
%cd rnn_testing

Cloning into 'rnn_testing'...
remote: Enumerating objects: 53, done.
remote: Counting objects: 100% (53/53), done.
remote: Compressing objects: 100% (36/36), done.
remote: Total 53 (delta 16), reused 52 (delta 15), pack-reused 0
Receiving objects: 100% (53/53), 5.77 MiB | 15.93 MiB/s, done.
Resolving deltas: 100% (16/16), done.
/content/rnn_testing


In [2]:
%load_ext autoreload


In [3]:
%%capture
!pip install lightning

In [4]:
from model import Model, train_one_batch
from model import *
from train_utils import Train_on_Batch
from typing import Any
# from lightning.pytorch.utilities.types import STEP_OUTPUT
import torch
import torch.nn as nn
from torch.nn import Embedding, Linear, LSTM, Module

from torch import tensor as T

import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import Dataset

# import lightning as L
from torch.utils.data import TensorDataset, DataLoader
from tqdm.notebook import tqdm

import matplotlib.pyplot as plt
import seaborn as sns

import typing


import yaml

#CODE

In [5]:
word_list_train = "data/250k_train.txt"
word_list_val = "data/250k_test.txt"
number_games = 10
model = Model("big_embed")


In [6]:
test_data_generator = Train_on_Batch(word_list_val, model, 500)
validate_set = test_data_generator.generate_data()

Streaming output truncated to the last 5000 lines.
p
['p']
tensor([27, 27, 27, 27, 27, 16, 27, 27, 27, 27, 27, 27])
Tries remaining : 5
p
['p']
tensor([27, 27, 27, 27, 27, 16, 27, 27, 27, 27, 27, 27])
Tries remaining : 4
p
['p']
tensor([27, 27, 27, 27, 27, 16, 27, 27, 27, 27, 27, 27])
Tries remaining : 3
p
['p']
tensor([27, 27, 27, 27, 27, 16, 27, 27, 27, 27, 27, 27])
Tries remaining : 2
p
['p']
tensor([27, 27, 27, 27, 27, 16, 27, 27, 27, 27, 27, 27])
Tries remaining : 1
p
['p']
tensor([27, 27, 27, 27, 27, 16, 27, 27, 27, 27, 27, 27])
chessplayers
Now Play
Tries remaining : 6
p
['p']
tensor([27, 27, 27, 27, 27, 27, 27, 27, 27])
Tries remaining : 5
p
['p']
tensor([27, 27, 27, 27, 27, 27, 27, 27, 27])
Tries remaining : 4
p
['p']
tensor([27, 27, 27, 27, 27, 27, 27, 27, 27])
Tries remaining : 3
p
['p']
tensor([27, 27, 27, 27, 27, 27, 27, 27, 27])
Tries remaining : 2
p
['p']
tensor([27, 27, 27, 27, 27, 27, 27, 27, 27])
Tries remaining : 1
p
['p']
tensor([27, 27, 27, 27, 27, 27, 27, 27, 27])

In [ ]:
train_for = 5000 #! games
for i in range(500, train_for+500, 500):
    #! generate data for 500 games at a time, train on it and mve ahead.
    model.to('cpu')
    t_d_g = Train_on_Batch(word_list_train, model, i, verbose=False)
    training_data = t_d_g.generate_data()
    model.to('cuda')
    training_data = [i.to('cuda') for i in training_data]
    train_one_batch(model, training_data[0], training_data[1], training_data[2], 1000, torch.optim.NAdam(model.parameters(), lr = 5e-3))
    # pbar.set_description("%.3f Val Loss" % )

  0%|          | 0/1000 [00:00<?, ?it/s]

  0%|          | 0/1000 [00:00<?, ?it/s]

  0%|          | 0/1000 [00:00<?, ?it/s]

  0%|          | 0/1000 [00:00<?, ?it/s]

  0%|          | 0/1000 [00:00<?, ?it/s]