In [1]:
%load_ext autoreload
import torch
import torch.nn as nn
from torch.nn import Embedding, Linear, LSTM, Module

from torch import tensor as T

import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import Dataset

import lightning as L
from torch.utils.data import TensorDataset, DataLoader


import matplotlib.pyplot as plt
import seaborn as sns

import typing


import yaml
from model import Model
from train import Trainer

In [2]:
m = Model("base_config")
t = Trainer("rahul", m, 6)
t.play()

_____
Now Play
Tries remaining : 6
y
['y']
tensor([27, 27, 27, 27, 27])
_____
Tries remaining : 5
y
['y']
tensor([27, 27, 27, 27, 27])
_____
Tries remaining : 4
y
['y']
tensor([27, 27, 27, 27, 27])
_____
Tries remaining : 3
y
['y']
tensor([27, 27, 27, 27, 27])
_____
Tries remaining : 2
y
['y']
tensor([27, 27, 27, 27, 27])
_____
Tries remaining : 1
y
['y']
tensor([27, 27, 27, 27, 27])
_____
rahul


_____
Now Play
Tries remaining : 6
[tensor([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0, 27, 27, 27, 27, 27])] [tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.])]
JLIJLKDJLK
21
v
['v']
tensor([27, 27, 27, 27, 27])
_____
Tries remaining : 5
[tensor([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0, 27, 27, 27, 27, 27])] [tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 1., 0., 0., 0., 0.])]
JLIJLKDJLK
3
d
['d', 'v']
tensor([27, 27, 27, 27, 27])
_____
Tries remaining : 4
[tensor([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0, 27, 27, 27, 27, 27])] [tensor([0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 1., 0., 0., 0., 0.])]
JLIJLKDJLK
5
f
['d', 

_____
Now Play
Tries remaining : 6
JLIJLKDJLK
21
v
['v']
tensor([27, 27, 27, 27, 27])
_____
Tries remaining : 5
JLIJLKDJLK
6
g
['v', 'g']
tensor([27, 27, 27, 27, 27])
_____
Tries remaining : 4
JLIJLKDJLK
6
g
['v', 'g']
tensor([27, 27, 27, 27, 27])
_____
Tries remaining : 3
JLIJLKDJLK
6
g
['v', 'g']
tensor([27, 27, 27, 27, 27])
_____
Tries remaining : 2
JLIJLKDJLK
6
g
['v', 'g']
tensor([27, 27, 27, 27, 27])
_____
Tries remaining : 1
JLIJLKDJLK
6
g
['v', 'g']
tensor([27, 27, 27, 27, 27])
_____
rahul
