In [2]:
from model import Model, train_one_batch
from model import *
from train_utils import Train_on_Batch, Evaluator

In [ ]:
# validate()

In [3]:
from typing import Any
from lightning.pytorch.utilities.types import STEP_OUTPUT
import torch
import torch.nn as nn
from torch.nn import Embedding, Linear, LSTM, Module

from torch import tensor as T

import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import Dataset

import lightning as L
from torch.utils.data import TensorDataset, DataLoader
from tqdm.notebook import tqdm

import matplotlib.pyplot as plt
import seaborn as sns

import typing


import yaml
import gc

In [4]:
word_list_train = "data/250k_train.txt"
word_list_val = "data/250k_test.txt"
number_games = 10
model = Model("big_embed")


In [23]:
torch.cuda.mem_get_info()

(1416036352, 4095934464)

In [22]:
model.to('cpu')
# training_data_generator = Train_on_Batch(word_list_train, model, 10000)
test_data_generator = Train_on_Batch(word_list_val, model, 500) 
validate_set = test_data_generator.generate_data()

_______________
Now Play
Tries remaining : 6
i
['i']
tensor([27,  9, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27])
Tries remaining : 6
p
['p', 'i']
tensor([27,  9, 16, 16, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27])
Tries remaining : 6
c
['p', 'i', 'c']
tensor([27,  9, 16, 16, 27,  3, 27, 27, 27, 27, 27,  3, 27, 27, 27])
Tries remaining : 6
o
['p', 'i', 'c', 'o']
tensor([27,  9, 16, 16, 15,  3, 27, 27, 27, 27, 27,  3, 27, 27, 27])
Tries remaining : 6
t
['c', 'i', 'o', 'p', 't']
tensor([27,  9, 16, 16, 15,  3, 27, 27, 20, 27, 27,  3, 27, 27, 27])
Tries remaining : 6
n
['c', 'i', 'n', 'o', 'p', 't']
tensor([27,  9, 16, 16, 15,  3, 27, 27, 20, 27, 27,  3, 27, 27, 27])
Tries remaining : 5
a
['a', 'c', 'i', 'n', 'o', 'p', 't']
tensor([27,  9, 16, 16, 15,  3, 27,  1, 20, 27,  1,  3, 27,  1, 27])
Tries remaining : 5
s
['a', 'c', 'i', 'n', 'o', 'p', 's', 't']
tensor([27,  9, 16, 16, 15,  3, 27,  1, 20, 27,  1,  3, 27,  1, 27])
Tries remaining : 4
d
['a', 'c', 'd', 'i', 'n', 'o', 'p', '

In [24]:
train_for = 5000 #! games
model.to('cpu')
for i in range(500, train_for+500, 500):
    #! generate data for 500 games at a time, train on it and mve ahead.
    
    t_d_g = Train_on_Batch(word_list_train, model, i, verbose=False)
    training_data = t_d_g.generate_data()
    model.to('cuda')
    training_data = [i.to('cuda') for i in training_data]
    train_one_batch(model, training_data[0], training_data[1], training_data[2], 1000, torch.optim.NAdam(model.parameters(), lr = 5e-3))
    model.to('cpu')
    # del model
    gc.collect()
    torch.cuda.empty_cache()

    
    # pbar.set_description("%.3f Val Loss" % )
    


  0%|          | 0/1000 [00:00<?, ?it/s]

  0%|          | 0/1000 [00:00<?, ?it/s]

  0%|          | 0/1000 [00:00<?, ?it/s]

  0%|          | 0/1000 [00:00<?, ?it/s]

OutOfMemoryError: CUDA out of memory. Tried to allocate 1.76 GiB (GPU 0; 3.81 GiB total capacity; 2.57 GiB already allocated; 816.44 MiB free; 2.89 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

In [13]:
torch.save(model, 'model_1000.pt')

In [5]:
model = Model("big_embed")
model.to('cpu')
DataGen = Train_on_Batch(word_list_train, model, 1000, verbose=False)
dataset = DataGen.generate_data()
# dataset = (i.to('cuda') for i in dataset)

_____
______
________
________
________
_______
_________
_______
________
__________
__________
_________________
_______
__________
___________
________
____
_____________
_________
__________
_______
___________
_______
____________
___________
_________
__________
___________
______
_______________
_______
____________
____
_____
______
___________
____________
__________
__________
____________
____
_____
________
__________
_____
______________
______
______
__________
__________
________
__________
__________
______
_____________
_________________
______
_____
__________
______
________
______
_________
______
______
_____________
_________
__________________
_________________
____
_______
____
_______
____________
___________
_______
_____
_______
______
_______
_______
_________
______________
______
_______
___________
___________
__________
________
_________
________
_______
__________
__________
________
_______________
____________
___________
_________
_____________
____

In [6]:
model.to('cuda')
dataset = [i.to('cuda') for i in dataset]

In [7]:
print([dataset[x].size() for x in range(3)])

[torch.Size([7070, 30]), torch.Size([7070, 26]), torch.Size([7070, 26])]


In [12]:

train_one_batch(model, dataset[0], dataset[1], dataset[2], 5000, torch.optim.Adagrad(model.parameters(),lr=1e-3))

  0%|          | 0/5000 [00:00<?, ?it/s]

KeyboardInterrupt: 

In [8]:
model.to('cpu')
DataGen.generate_data()

_______
Now Play
Tries remaining : 6
e
['e']
tensor([27, 27, 27,  5, 27, 27, 27])
___e___
Tries remaining : 6
a
['a', 'e']
tensor([27, 27, 27,  5, 27, 27, 27])
___e___
Tries remaining : 5
a
['a', 'e']
tensor([27, 27, 27,  5, 27, 27, 27])
___e___
Tries remaining : 4
a
['a', 'e']
tensor([27, 27, 27,  5, 27, 27, 27])
___e___
Tries remaining : 3
a
['a', 'e']
tensor([27, 27, 27,  5, 27, 27, 27])
___e___
Tries remaining : 2
a
['a', 'e']
tensor([27, 27, 27,  5, 27, 27, 27])
___e___
Tries remaining : 1
a
['a', 'e']
tensor([27, 27, 27,  5, 27, 27, 27])
___e___
toreros
______
Now Play
Tries remaining : 6
e
['e']
tensor([27, 27, 27, 27, 27, 27])
______
Tries remaining : 5
e
['e']
tensor([27, 27, 27, 27, 27, 27])
______
Tries remaining : 4
e
['e']
tensor([27, 27, 27, 27, 27, 27])
______
Tries remaining : 3
e
['e']
tensor([27, 27, 27, 27, 27, 27])
______
Tries remaining : 2
e
['e']
tensor([27, 27, 27, 27, 27, 27])
______
Tries remaining : 1
e
['e']
tensor([27, 27, 27, 27, 27, 27])
______
ryazan
___

(tensor([[ 0,  0,  0,  ..., 27, 27, 27],
         [ 0,  0,  0,  ..., 27, 27, 27],
         [ 0,  0,  0,  ..., 27, 27, 27],
         ...,
         [ 0,  0,  0,  ..., 27,  5, 27],
         [ 0,  0,  0,  ..., 27,  5, 27],
         [ 0,  0,  0,  ..., 27,  5, 27]]),
 tensor([[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 1.],
         [0., 0., 0.,  ..., 0., 0., 1.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]]),
 tensor([[0.0909, 0.0000, 0.0909,  ..., 0.0909, 0.0000, 0.0000],
         [0.0909, 0.0000, 0.0909,  ..., 0.0909, 0.0000, 0.0000],
         [0.0909, 0.0000, 0.0909,  ..., 0.0909, 0.0000, 0.0000],
         ...,
         [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000]]))